### ISSUE TITLE
New classes - package

### ISSUE THREAD

**Issue by Vieja** [Ppiotr98/BuildingInfo#5]
Gdzie utworzymy podstawowe klasy (Lokacja, Budynek etc.) żeby to miało sens i dobrze wyglądało?
Mamy aktualnie 3 package: app, logic i rest. Możemy stworzyć nowy do przechowywania klas albo dać do istniejącego, np logic.

**Comment by Vieja** [comment]
![image](https://user-images.githubusercontent.com/35605153/67939344-a070e280-fbd1-11e9-9bc8-01790ca3350a.png)

**Comment by daniktl** [comment]
Nigdy nie pisałem w Javie a więc najważniejsze pytanie czy jest jakaś róznica ze względu na działanie całego programu?

**Comment by Vieja** [comment]
Dla Javy to nie ma kompletnie znaczenia, wszystko zadziała, chodzi tylko o naszą preferencję.

**Comment by daniktl** [comment]
No to jabym preferował app

**Comment by Vieja** [comment]
Ok
